cloudfoundry/multiapps-cli-plugin

- commands/base_command.go
- commands/download_mta_op_logs_command_test.go
- commands/mta_command_test.go
- commands/mta_operations_command_test.go
- commands/mtas_command_test.go
> Print warning when using a custom deploy service URL

- util/deploy_service_url_calculator.go
- util/deploy_service_url_calculator_test.go
- util/fakes/fake_http_simple_executor.go
> Improve messages in case the Deploy Service URL cannot be computed

- clients/baseclient/client_error.go
- clients/cfrestclient/operations/get_shared_domains_responses.go
- clients/mtaclient/operations/execute_operation_action_responses.go
- clients/mtaclient/operations/get_csrf_token_responses.go
- clients/mtaclient/operations/get_info_responses.go
- clients/mtaclient/operations/get_mta_files_responses.go
- clients/mtaclient/operations/get_mta_operation_log_content_responses.go
- clients/mtaclient/operations/get_mta_operation_logs_responses.go
- clients/mtaclient/operations/get_mta_operation_responses.go
- clients/mtaclient/operations/get_mta_operations_responses.go
- clients/mtaclient/operations/get_mta_responses.go
- clients/mtaclient/operations/get_mtas_responses.go
- clients/mtaclient/operations/get_operation_actions_responses.go
- clients/mtaclient/operations/start_mta_operation_responses.go
- clients/mtaclient/operations/upload_mta_file_responses.go
- clients/restclient/operations/get_csrf_token_responses.go
- clients/restclient/operations/purge_configuration_responses.go
> display response in REST error cases

- commands/base_command.go
> Add parameters in query for ongoing operations

- clients/baseclient/client_error.go
- clients/mtaclient/operations/get_info_responses.go
- clients/mtaclient/operations/get_mta_files_responses.go
- clients/mtaclient/operations/get_mta_operation_logs_responses.go
- clients/mtaclient/operations/get_mta_operation_responses.go
- clients/mtaclient/operations/get_mta_operations_responses.go
- clients/mtaclient/operations/get_mta_responses.go
- clients/mtaclient/operations/get_mtas_responses.go
- clients/mtaclient/operations/upload_mta_file_responses.go
- commands/test_token_factory.go
- testutil/exiter.go
- util/deploy_service_url_calculator.go
- util/deploy_service_url_calculator_test.go
- util/fakes/fake_http_simple_executor.go
Format all go code, except for /vendor folder
> format the code

- CONTRIBUTING.md
- README.md
- revert back to * lists
- add a section about cloning the project in your Go Workspace
LMCROSSITXSADEPLOY-1125
> update the documentation 2

- CONTRIBUTING.md
update contributing with beginner issues section like the other projects
LMCROSSITXSADEPLOY-1125
> update contributing with beginner issues section

- commands/base_command.go
> Increase TLS Handshake timeout

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
> Allow users to skip the ownership validation

- commands/base_command.go
- commands/deploy_command.go
- commands/deploy_command_test.go
- commands/download_mta_op_logs_command.go
- commands/download_mta_op_logs_command_test.go
- commands/flags_parser.go
- commands/mta_command.go
- commands/mta_command_test.go
- commands/mta_operations_command.go
- commands/mta_operations_command_test.go
- commands/mtas_command.go
- commands/mtas_command_test.go
- commands/purge_config_command.go
- commands/purge_config_command_test.go
- commands/undeploy_command.go
- util/archive_builder.go
- util/archive_builder_test.go
- util/archive_handler.go
- util/mta_deployment_descriptor.go
- util/mta_manifest.go
- Add support for selective deployment
- Refactors the command-line arguments parsing
> Selective deployment

- commands/deploy_command.go
- util/archive_builder.go
- util/builders.go
> Add support for all-modules and all-resources

- commands/file_uploader_test.go
> Fix vetting

- cli/fakes/fake_cli_connection_builder.go
- commands/mta_command.go
- commands/mta_command_test.go
> Fix 'cf mta' command when there are non-staged apps

- commands/execution_monitor.go
> Stop DDoS attacks against the multiapps-controller

- commands/base_command.go
- commands/deploy_command.go
- commands/deploy_command_test.go
- commands/file_uploader.go
- util/file_splitter.go
> Allow configuration of MTAR chunk size

- commands/base_command.go
- commands/file_uploader.go
- configuration/configuration.go
- configuration/configuration_suite_test.go
- configuration/configuration_test.go
- util/file_splitter.go
> Test retrieval of configuration variables

- .gitignore
- build.sh
- multiapps_plugin.go
JIRA:LMCROSSITXSADEPLOY-1397 Integrate MTA CLI plugin in CF community
plugin repo
> Change name of plugin MtaPlugin to multiapps

- .gitignore
- build.sh
JIRA:LMCROSSITXSADEPLOY-1397 Integrate MTA CLI plugin in CF community
plugin repo
> Keep old file names of plugin and add new platforms in build.sh

- .gitignore
- build.sh
This changes the build.sh script to output in the build folder and also
include some extra metadata files such as version and changelog for the
specific version.
LMCROSSITXSADEPLOY-1397
> enhance build script to output in specific folder

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
Add two new parameters:
--verify-archive-signature -> Using Symantec certificate and default "SAP SE" CN
> Add verify-archive-signature parameter

- README.md
- commands/file_uploader.go
- configuration/configuration.go
- util/file_splitter.go
This commit adds a check for the chunk size(if specified). This is needed in order to prevent DDoS attack if the chunk size is very low.
> Add check for chunk size

- clients/baseclient/base_client.go
- clients/cfrestclient/fakes/fake_cloud_foundry_client.go
- clients/client_factory.go
- clients/csrf/default_csrf_token_updater.go
- clients/csrf/fakes/fake_csrf_token_fetcher.go
- clients/mtaclient/mta_rest_client.go
- clients/mtaclient/operations/upload_mta_file_parameters.go
- clients/restclient/rest_client.go
- clients/restclient/rest_client_test.go
- clients/restclient/retryable_rest_client.go
- clients/restclient/retryable_rest_client_test.go
- commands/base_command.go
- commands/base_command_test.go
- commands/blue_green_deploy_command.go
- commands/deploy_command.go
- commands/file_uploader.go
- commands/file_uploader_test.go
- commands/test_client_factory.go
- util/archive_handler.go
Add --strategy flag to deploy command
> Add strategy flag to deploy

- commands/action.go
- commands/blue_green_deploy_command.go
- commands/deploy_command.go
- commands/deploy_command_test.go
- commands/deployment_strategy.go
- commands/deployment_strategy_test.go
- commands/execution_monitor.go
- commands/fakes/fake_process_type_provider.go
- util/archive_builder.go
> Update strategy flag handling

- clients/mtaclient/fakes/fake_mta_client_builder.go
- clients/mtaclient/fakes/fake_mta_client_operations.go
- clients/mtaclient/mta_client_operations.go
- clients/mtaclient/mta_rest_client.go
- clients/mtaclient/operations/get_mta_operations_parameters.go
- clients/mtaclient/retryable_mta_rest_client.go
- commands/base_command.go
- commands/base_command_test.go
- commands/deploy_command_test.go
- commands/download_mta_op_logs_command.go
- commands/download_mta_op_logs_command_test.go
- commands/mta_operations_command.go
- commands/mta_operations_command_test.go
Extend the commands for dmol and mta-ops to accept additional arg for
mta-id. JIRA: LMCROSSITXSADEPLOY-1723 and LMCROSSITXSADEPLOY-1578
> Add --mta-id flag for dmol and mta-ops

- commands/download_mta_op_logs_command.go
- commands/download_mta_op_logs_command_test.go
> Add .log extension to log files

- commands/deploy_command.go
- commands/deploy_command_test.go
- commands/undeploy_command.go
Log the operation id before monitoring the deploy/bg-deploy execution.
JIRA: LMCROSSITXSADEPLOY-1748
> Log operation id in the beginning of (bg-)deploy

- commands/undeploy_command_test.go
> Rewrite unit tests for undeploy command

- configuration/configuration.go
> Treat empty environment variables as unset

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
- commands/download_mta_op_logs_command_test.go
- commands/file_uploader_test.go
- commands/undeploy_command.go
- util/digest_test.go
> Add delete service keys

- util/archive_builder.go
- util/archive_builder_test.go
Create directory for each module and put all related artifacts there
> Fix overriding of artifacts with same filename

- .travis.yml
- util/archive_builder.go
- util/archive_builder_test.go
Replace the usage of filepath.Join with concatenation of "/".
JIRA: LMCROSSITXSADEPLOY-2061
> Create unix-normalized paths for MANIFEST.MF

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
- util/deploy_service_url_calculator.go
- util/deploy_service_url_calculator_test.go
> updated old help messages

- util/deploy_service_url_calculator.go
> Retry calls which find DS URL

- clients/mtaclient/fakes/fake_mta_client_operations.go
- clients/mtaclient/mta_client_operations.go
- clients/mtaclient/mta_rest_client.go
- clients/mtaclient/operations/upload_mta_file_parameters.go
- clients/mtaclient/retryable_mta_rest_client.go
- commands/file_uploader.go
- commands/file_uploader_test.go
- util/digest.go
- util/file_splitter.go
Add the file size as a header, so that the new upload mechanism (without
a temporary file) can be used.
> Add custom header to POST /files requests

- commands/file_uploader.go
> Call os.Open sequentially for file chunks

- commands/deploy_command.go
- commands/deploy_command_test.go
- commands/undeploy_command.go
- commands/undeploy_command_test.go
See cloudfoundry-incubator/multiapps-controller/pull/1036
> Don't print operation ID

- clients/baseclient/client_util.go
> Log message on failed call

- README.md
I found this representation more intuitive as you don't need to go to another page to search for the right binary. I hope you do too :)
> Add table with links

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
- commands/deployment_strategy.go
- commands/deployment_strategy_test.go
- commands/mta_command.go
- commands/mta_command_test.go
- ui/ui.go
LMCROSSITXSADEPLOY-2492
Skip idle applications' start if "skip-idle-start" parameter is provided.
> Skip idle start

- .gitignore
- clients/mtaclient/operations/upload_mta_archive_from_url_parameters.go
- commands/blue_green_deploy_command.go
- commands/deploy_command.go
- commands/deploy_command_test.go
> Encode file url as base64 string

- commands/undeploy_command.go
https://github.com/cloudfoundry/multiapps-cli-plugin/issues/143
> Print org and space during undeploy

- clients/csrf/csrf_token_manager_test.go
- clients/csrf/default_csrf_token_manager.go
- clients/csrf/transport.go
Backlog item: LMCROSSITXSADEPLOY-2668
> Fix first request failure during deploy with url

- clients/mtaclient/mta_rest_client.go
- clients/mtaclient_v2/fakes/fake_mta_v2_client_builder.go
- clients/mtaclient_v2/fakes/fake_mta_v2_client_operations.go
- commands/base_command.go
- commands/deployment_strategy_test.go
- commands/download_mta_op_logs_command.go
- commands/download_mta_op_logs_command_test.go
- commands/mta_command_test.go
- multiapps_plugin.go
- testutil/transport.go
- util/archive_builder.go
- util/archive_builder_test.go
- util/archive_handler.go
- util/digest_test.go
- util/mta_manifest.go
> Add error check on getting mta op log content

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
> Remove verify-archive-signature flag

- README.md
- commands/file_uploader.go
- configuration/configuration.go
- configuration/properties/upload_chunks_sequentially_property.go
Upload chunks in parallel by default
> Invert default chunk upload logic

- commands/file_uploader.go
> Do not reupload files with same digest but different names

- build.sh
> Make statically linked binaries the default

- commands/blue_green_deploy_command.go
- commands/deploy_command.go
https://github.com/cloudfoundry/multiapps-controller/pull/1503
LMCROSSITXSADEPLOY-2424
> Added new 4 parameters for timeout

- .github/workflows/pull-request-build.yml
- clients/csrf/default_csrf_token_fetcher.go
- go.mod
> Bump go to 1.24
